NIM-2349 Added more logging
clearpathrobotics/multimaster_fkie pull request #1
Opened 2016-10-19 20:26 UTC by deng02

- Log to track what masters are being synchronized and when
- Log to track number of UDP messages sent
- Log to track exactly what publisher, subscribers and services
  are being (un)registered

Testing:
- verify system runs

2016-10-19 20:27 UTC, deng02 commented
I am not intending to merge this into Master as I want to keep this change and upstream separate.  Instead I have created tag 0.6.1-2349 to use in the distrubtion.yaml as a way to bring this change into the devel bundle.

2016-10-20 13:03 UTC, sjfwilson requested changes

2016-10-20 13:03 UTC, sjfwilson commented on master_discovery_fkie/src/master_discovery_fkie/master_discovery.py
> +                            msg = "DiscoveredMaster[%s] Returned a Master Name of NONE" % self.monitoruri
cut/paste error: Use `self.mastername`

2016-10-20 13:03 UTC, sjfwilson commented on master_discovery_fkie/src/master_discovery_fkie/master_discovery.py
> +                for (k, v) in self.masters.iteritems():
Replacement of `_` with `k` was cleanup/readability motivated, or was there an issue with it?

2016-10-20 13:03 UTC, sjfwilson commented on master_discovery_fkie/src/master_discovery_fkie/master_discovery.py
> +                delta = current - self.msg_counter_sent_group_last
Noting that `delta` in this method (both uses) can be negative; reporting this is fine. Is this what you wanted?

2016-10-20 13:03 UTC, sjfwilson commented on master_sync_fkie/src/master_sync_fkie/sync_thread.py
> +                rospy.loginfo("SyncThread[%s]: UPUB %s[%s] %s[%s]",
Consider changing `UPUB` to `UNPUB`, to add more context to the log line.

2016-10-20 13:03 UTC, sjfwilson commented on master_sync_fkie/src/master_sync_fkie/sync_thread.py
> +                rospy.loginfo("SyncThread[%s]: USUB %s[%s] %s[%s]",
Consider changing `USUB` to `UNSUB`, to add more context to the log line.

2016-10-20 13:03 UTC, sjfwilson commented on master_sync_fkie/src/master_sync_fkie/sync_thread.py
> +                rospy.loginfo("SyncThread[%s]: USRV %s[%s] %s[%s]",
Consider changing `USRV` to `UNSRV`, to add more context to the log line.

2016-10-20 13:03 UTC, sjfwilson commented on master_discovery_fkie/src/master_discovery_fkie/master_discovery.py
> +                    self.msg_counter_sent_address_last[k] = current
Where are the records removed from `self.msg_counter_sent_address` and `self.msg_counter_send_address_last`?
If not removing them, you can have stale data that you are reporting on.

2016-10-20 13:05 UTC, deng02 commented on master_discovery_fkie/src/master_discovery_fkie/master_discovery.py
> +                            msg = "DiscoveredMaster[%s] Returned a Master Name of NONE" % self.monitoruri
will do

2016-10-20 13:06 UTC, deng02 commented on master_discovery_fkie/src/master_discovery_fkie/master_discovery.py
> +                for (k, v) in self.masters.iteritems():
since I'm using the variable I wanted to remove the '_' name, which typically indicates an unused variable to get around pylint/pep8 warnings

2016-10-20 13:06 UTC, deng02 commented on master_discovery_fkie/src/master_discovery_fkie/master_discovery.py
> +                delta = current - self.msg_counter_sent_group_last
How can this be negative?

2016-10-20 13:07 UTC, deng02 commented on master_discovery_fkie/src/master_discovery_fkie/master_discovery.py
> +                    self.msg_counter_sent_address_last[k] = current
Ah - yes there is a place where a master needs to be removed; I will fix this

2016-10-20 13:07 UTC, deng02 commented on master_sync_fkie/src/master_sync_fkie/sync_thread.py
> +                rospy.loginfo("SyncThread[%s]: UPUB %s[%s] %s[%s]",
will do

2016-10-20 13:07 UTC, deng02 commented on master_sync_fkie/src/master_sync_fkie/sync_thread.py
> +                rospy.loginfo("SyncThread[%s]: USUB %s[%s] %s[%s]",
will do

2016-10-20 13:07 UTC, deng02 commented on master_sync_fkie/src/master_sync_fkie/sync_thread.py
> +                rospy.loginfo("SyncThread[%s]: USRV %s[%s] %s[%s]",
will do

2016-10-20 17:54 UTC, deng02 commented on master_discovery_fkie/src/master_discovery_fkie/master_discovery.py
> +                            msg = "DiscoveredMaster[%s] Returned a Master Name of NONE" % self.monitoruri
oh actually no this is correct. The monitor URI is meant to identify the DiscoveredMaster instance. The self.mastername is none in this case.

2016-10-20 20:35 UTC, deng02 commented
Made the change as per comments as well as a few others:
- Refactored the message counters into their own object for clarity
- To help gauge how much UDP traffic a master discovery node generates, we now output total number of UDP message sent overall, as well as total group/multicast and total unicast
- To help identify false offline by multimaster, logging PING output to IP addresses going offline

2016-10-21 19:27 UTC, sjfwilson requested changes

2016-10-21 19:27 UTC, sjfwilson commented on master_discovery_fkie/src/master_discovery_fkie/master_discovery.py
> +                            msg = "DiscoveredMaster[%s] Returned a Master Name of NONE" % self.monitoruri
Ah yes, I see that now. Apologies. This is fine.

2016-10-21 19:27 UTC, sjfwilson commented on master_discovery_fkie/src/master_discovery_fkie/master_discovery.py
> +        for k in self.num_per_address:
Could change this to be `for k, current in self.num_per_address.iteritems():` and save yourself the line below.
Also consider a more meaningful name than `k` for the key. Perhaps `address`?

2016-10-21 19:27 UTC, sjfwilson commented on master_discovery_fkie/src/master_discovery_fkie/master_discovery.py
> +            if address not in self.msg_counter_sent_address:
What this missed in migrating to using `self.msg_counter`?

Other than this immediate block, I do not see any other mention of `self.msg_counter_sent_address` in this PR.

2016-10-21 19:27 UTC, sjfwilson commented on master_discovery_fkie/src/master_discovery_fkie/master_discovery.py
> +                for (k, v) in self.masters.iteritems():
I do not see any usage of `k` in this block.

2016-10-21 19:27 UTC, sjfwilson commented on master_discovery_fkie/src/master_discovery_fkie/master_discovery.py
> +                for l in output.split('\n'):
Consider more meaningful loop variable name, `line` perhaps?

2016-10-24 18:13 UTC, deng02 commented on master_discovery_fkie/src/master_discovery_fkie/master_discovery.py
> +                for (k, v) in self.masters.iteritems():
You're right, will change this.

2016-10-24 18:16 UTC, deng02 commented on master_discovery_fkie/src/master_discovery_fkie/master_discovery.py
> +        for k in self.num_per_address:
done

2016-10-24 18:18 UTC, deng02 commented on master_discovery_fkie/src/master_discovery_fkie/master_discovery.py
> +            if address not in self.msg_counter_sent_address:
You are correct: fixed.

2016-10-24 18:19 UTC, deng02 commented on master_discovery_fkie/src/master_discovery_fkie/master_discovery.py
> +                for l in output.split('\n'):
done

2016-11-15 15:19 UTC, closed without merging